app:
  event-queue:
    enabled: true

background-executor:
  executor:
    task-size: 1
  enabled: true
  default-executor: cron
  time:
    in-seconds-time: 2
  cron:
    expression: "*/3 * * * * *"
